<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leon Noirclerc">
<meta name="dcterms.date" content="2026-05-18">
<meta name="description" content="Building a grounded, fast, efficient RAG system from scratch on a 16 GB MacBook. This post grows as the system grows: each new iteration on the pipeline lands as a new subsection with the numbers behind it.">

<title>A grounded RAG system, on a laptop – Leon Noirclerc</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-28b5350d053d3182e720a93c57f5f353.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-49926bd9bd355d484abe762a358f30da.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: cover.png;
      }
</style>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="A grounded RAG system, on a laptop – Leon Noirclerc">
<meta property="og:description" content="Building a grounded, fast, efficient RAG system from scratch on a 16 GB MacBook. This post grows as the system grows: each new iteration on the pipeline lands as a new subsection with the numbers behind it.">
<meta property="og:image" content="https://leonnoirclerc.github.io/posts/rag-on-a-laptop/pipeline.svg">
<meta property="og:site_name" content="Leon Noirclerc">
<meta name="twitter:title" content="A grounded RAG system, on a laptop – Leon Noirclerc">
<meta name="twitter:description" content="Building a grounded, fast, efficient RAG system from scratch on a 16 GB MacBook. This post grows as the system grows: each new iteration on the pipeline lands as a new subsection with the numbers behind it.">
<meta name="twitter:image" content="https://leonnoirclerc.github.io/posts/rag-on-a-laptop/pipeline.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Leon Noirclerc</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/leonnoirclerc"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">A grounded RAG system, on a laptop</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Building a grounded, fast, efficient RAG system from scratch on a 16 GB MacBook. This post grows as the system grows: each new iteration on the pipeline lands as a new subsection with the numbers behind it.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">rag-laptop</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Leon Noirclerc </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 18, 2026</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">May 20, 2026</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#grounded-fast-efficient" id="toc-grounded-fast-efficient" class="nav-link active" data-scroll-target="#grounded-fast-efficient">Grounded, Fast, Efficient</a></li>
  <li><a href="#the-stack" id="toc-the-stack" class="nav-link" data-scroll-target="#the-stack">The stack</a></li>
  <li><a href="#the-parsing" id="toc-the-parsing" class="nav-link" data-scroll-target="#the-parsing">The parsing</a>
  <ul class="collapse">
  <li><a href="#two-routes-docling-offers" id="toc-two-routes-docling-offers" class="nav-link" data-scroll-target="#two-routes-docling-offers">Two routes Docling offers</a></li>
  <li><a href="#what-each-route-costs-on-our-corpus" id="toc-what-each-route-costs-on-our-corpus" class="nav-link" data-scroll-target="#what-each-route-costs-on-our-corpus">What each route costs on our corpus</a></li>
  <li><a href="#inside-the-traditional-pipeline" id="toc-inside-the-traditional-pipeline" class="nav-link" data-scroll-target="#inside-the-traditional-pipeline">Inside the traditional pipeline</a></li>
  <li><a href="#where-is-the-bottleneck" id="toc-where-is-the-bottleneck" class="nav-link" data-scroll-target="#where-is-the-bottleneck">Where is the bottleneck?</a></li>
  <li><a href="#first-improvement-the-code-formula-model" id="toc-first-improvement-the-code-formula-model" class="nav-link" data-scroll-target="#first-improvement-the-code-formula-model">First improvement: the code &amp; formula model</a></li>
  <li><a href="#second-improvement-the-layout-detector" id="toc-second-improvement-the-layout-detector" class="nav-link" data-scroll-target="#second-improvement-the-layout-detector">Second improvement: the layout detector</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul></li>
  <li><a href="#the-embedding" id="toc-the-embedding" class="nav-link" data-scroll-target="#the-embedding">The embedding</a>
  <ul class="collapse">
  <li><a href="#the-candidates-models" id="toc-the-candidates-models" class="nav-link" data-scroll-target="#the-candidates-models">The candidates models</a></li>
  <li><a href="#dense-recallk" id="toc-dense-recallk" class="nav-link" data-scroll-target="#dense-recallk">Dense recall@k</a></li>
  <li><a href="#hybrid-retrieval" id="toc-hybrid-retrieval" class="nav-link" data-scroll-target="#hybrid-retrieval">Hybrid retrieval</a></li>
  <li><a href="#quantization" id="toc-quantization" class="nav-link" data-scroll-target="#quantization">Quantization</a></li>
  <li><a href="#indexing-speed" id="toc-indexing-speed" class="nav-link" data-scroll-target="#indexing-speed">Indexing speed</a></li>
  <li><a href="#the-pick" id="toc-the-pick" class="nav-link" data-scroll-target="#the-pick">The pick</a></li>
  </ul></li>
  <li><a href="#reranking" id="toc-reranking" class="nav-link" data-scroll-target="#reranking">Reranking</a>
  <ul class="collapse">
  <li><a href="#the-multilingual-options" id="toc-the-multilingual-options" class="nav-link" data-scroll-target="#the-multilingual-options">The multilingual options</a></li>
  <li><a href="#hit1-across-the-four-multilingual-families" id="toc-hit1-across-the-four-multilingual-families" class="nav-link" data-scroll-target="#hit1-across-the-four-multilingual-families">Hit@1 across the four multilingual families</a></li>
  <li><a href="#what-we-ship" id="toc-what-we-ship" class="nav-link" data-scroll-target="#what-we-ship">What we ship</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>This is a post about building a grounded RAG system from scratch. The goal is simple to state: point it at a stack of PDFs, ask a question in natural language, get back an answer together with the exact bounding box on the exact page that answer came from. The constraint is what makes it interesting. The whole thing has to run on the laptop I’m writing on, a MacBook Pro M2 with 16 GB of unified memory, no cloud GPU.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gpu_poor.png" class="img-fluid figure-img"></p>
<figcaption>The main constraint: we are GPU poor :(</figcaption>
</figure>
</div>
<p>The post starts from the simplest version of the pipeline that hits the goal, then iterates from there. Each iteration is its own subsection, with the reasoning, the numbers, and a link to whatever code or model weights came out of it.</p>
<section id="grounded-fast-efficient" class="level2">
<h2 class="anchored" data-anchor-id="grounded-fast-efficient">Grounded, Fast, Efficient</h2>
<p>Three goals, easy to state.</p>
<p><strong>Grounded.</strong> Every answer has to point back to the bounding box on the page it came from. Not a citation in plain text, a visible region on the rendered page, one you can click on and verify.</p>
<p><strong>Fast.</strong> Sub-second retrieval on a single query. Anything slower turns iteration into a chore, and this is a system meant to be iterated on a lot.</p>
<p><strong>Efficient.</strong> Fits in 16 GB. Runs alongside a browser, an editor, and the Docker stack the system itself depends on. No cloud GPU, no API key billed by the token. The whole thing needs to be self-contained enough that someone could clone the repo and have it work.</p>
</section>
<section id="the-stack" class="level2">
<h2 class="anchored" data-anchor-id="the-stack">The stack</h2>
<p>Anything we want to retrieve later, we have to store first. The system has three layers underneath: the binary files that come in, the structured representation we extract from them, and the vector index we build on top to make them searchable.</p>
<p><strong>Document storage.</strong> PDFs land in a blob store keyed by a UUID. Local case is just a directory; behind a thin <a href="https://github.com/fsspec/filesystem_spec">fsspec</a> wrapper so the day this needs to live in S3 instead, the change is a config swap.</p>
<p><strong>The structured database.</strong> A document has pages, each page has layout elements (paragraphs, headings, tables, figures, formulas, code blocks), and each element has one or more bounding boxes. That hierarchy lives in <a href="https://www.postgresql.org/">Postgres</a> via <a href="https://www.sqlalchemy.org/">SQLAlchemy</a>. On top of the elements come <strong>chunks</strong>, the unit the embedder sees and retrieval returns. Each chunk keeps a link back to the elements it covers, so a hit can be traced to specific page regions.</p>
<p><strong>The vector store.</strong> One vector per chunk, in <a href="https://qdrant.tech/">Qdrant</a>, keyed by chunk UUID, with a small payload (just the parent document id, for filtering). Everything else stays in Postgres.</p>
<p><strong>The embedder.</strong> Starting point is <a href="https://huggingface.co/BAAI/bge-m3">bge-m3</a>: 1024-dimensional vectors, ~1.1 GB resident at fp16 on Apple Silicon, a defensible default for general-purpose retrieval.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pipeline.svg" class="img-fluid figure-img"></p>
<figcaption>Pipeline overview: blob storage, Postgres with the document, page, and element hierarchy, and the vector database side by side.</figcaption>
</figure>
</div>
<p>The parser is where the real work begins, and that’s where the rest of this post lives.</p>
</section>
<section id="the-parsing" class="level2">
<h2 class="anchored" data-anchor-id="the-parsing">The parsing</h2>
<p><a href="https://github.com/docling-project/docling">Docling</a> is the tool we use to turn a PDF into a structured tree. That tree is the input to everything that follows: chunking, embedding, retrieval, grounding. It controls what each later stage can see. So before we build any of that on top, we should know how the parsing actually behaves on our corpus, what it costs, and whether the defaults are the right ones.</p>
<section id="two-routes-docling-offers" class="level3">
<h3 class="anchored" data-anchor-id="two-routes-docling-offers">Two routes Docling offers</h3>
<p>Docling exposes two top-level ways to turn a page into structured content.</p>
<p>The first is the <strong>traditional pipeline</strong>: a layered stack of small specialist models running in sequence. A CNN layout detector finds text blocks, tables, pictures, formulas, and code. A separate model parses table structure into rows and columns. A small vision-language model runs on cropped code and formula regions to turn them into LaTeX or source text. A figure classifier labels pictures by type. The text inside each block comes from the PDF’s own text layer, extracted by a dedicated parser. Each stage has one job, runs on one slice of the page, and produces one piece of the final document.</p>
<p>The second is the <strong>VLM pipeline</strong>: one large vision-language model gets the rendered page image and emits the entire structured document for that page in one shot. No separate layout step. No separate table parsing. The model decides where the text blocks are, where the tables are, what the cells contain, which regions are pictures, all at once. The Docling-blessed model for this path is <a href="https://huggingface.co/ibm-granite/granite-docling-258M">Granite-Docling-258M</a>, available as an MLX export for Apple Silicon.</p>
<p>Both routes produce a structurally similar <code>DoclingDocument</code>, and Docling lets us swap between them by changing a single configuration object.</p>
</section>
<section id="what-each-route-costs-on-our-corpus" class="level3">
<h3 class="anchored" data-anchor-id="what-each-route-costs-on-our-corpus">What each route costs on our corpus</h3>
<p>Seven research papers, 155 pages total. Each variant runs each PDF once untimed (warmup) then three times measured; we report the median wall time per variant per doc, summed across the corpus. All on Apple Silicon. Code: <a href="https://github.com/leonnoirclerc/rag/tree/d72e8993f047c6b559062edfb7e5156299e8f33c/benchmark/pdf_pipeline"><code>benchmark/pdf_pipeline/</code></a>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th style="text-align: right;">Total wall (s)</th>
<th style="text-align: right;">Per-page (s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>traditional</td>
<td style="text-align: right;">582.4</td>
<td style="text-align: right;">3.8</td>
</tr>
<tr class="even">
<td>VLM (Granite-Docling-258M MLX)</td>
<td style="text-align: right;">~2 000</td>
<td style="text-align: right;">~13</td>
</tr>
</tbody>
</table>
<p>Roughly one order of magnitude. The traditional pipeline does cheap text extraction on the bulk of the page (the prose, where the PDF already has a clean text layer) and saves the expensive VLM passes for the few regions that genuinely need them: the cropped code and formula boxes. The VLM pipeline pays the full VLM cost on every page to re-derive content that is already sitting in the PDF text stream. For our corpus, which is born-digital papers with clean text layers, the traditional pipeline is the right trade.</p>
</section>
<section id="inside-the-traditional-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="inside-the-traditional-pipeline">Inside the traditional pipeline</h3>
<p>The traditional pipeline is a pipeline in the literal sense: pages stream through ordered stages, with multiple pages in different stages at once. Each stage owns one piece of the page-to-document translation, and each one is a place we can attack independently.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>What it does</th>
<th>Implementation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>page_parse</code></td>
<td>Render the page to an image at two scales, extract text cells with bboxes from the PDF text layer</td>
<td>pypdfium2 (C++) for rendering, <a href="https://github.com/docling-project/docling-parse">docling-parse</a> (C++) for text extraction</td>
</tr>
<tr class="even">
<td><code>layout</code></td>
<td>Detect text blocks, tables, pictures, formulas, code regions on the rendered page</td>
<td>Object-detection CNN running on MPS</td>
</tr>
<tr class="odd">
<td><code>table_structure</code></td>
<td>Parse the cell grid of each detected table</td>
<td>TableFormer V1, CPU on Apple Silicon</td>
</tr>
<tr class="even">
<td><code>doc_enrich</code></td>
<td>Crop each detected code or formula region and run a VLM on it to get LaTeX or source</td>
<td>Granite-Docling-258M, MLX</td>
</tr>
<tr class="odd">
<td><code>reading_order</code></td>
<td>Decide the order in which elements appear in the final document</td>
<td>CPU heuristics</td>
</tr>
<tr class="even">
<td><code>doc_assemble</code></td>
<td>Build the final <code>DoclingDocument</code> tree</td>
<td>Pure Python</td>
</tr>
</tbody>
</table>
<p>Picture classification piggybacks on <code>doc_enrich</code>. Tables are a stage of their own. Code and math sit inside <code>doc_enrich</code> because they share the same VLM and the same per-region inference path.</p>
</section>
<section id="where-is-the-bottleneck" class="level3">
<h3 class="anchored" data-anchor-id="where-is-the-bottleneck">Where is the bottleneck?</h3>
<p>Per-page wall time across the corpus, with tables on:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th style="text-align: right;">Per-page wall (ms)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>page_parse</code></td>
<td style="text-align: right;">500</td>
</tr>
<tr class="even">
<td><code>layout</code></td>
<td style="text-align: right;">497</td>
</tr>
<tr class="odd">
<td><code>table_structure</code></td>
<td style="text-align: right;">544</td>
</tr>
<tr class="even">
<td><code>doc_enrich</code></td>
<td style="text-align: right;"><strong>2 936</strong></td>
</tr>
</tbody>
</table>
<p><code>doc_enrich</code> dominates the average. But the average hides the most useful fact: the bottleneck depends on the document. Per-page wall time, split per paper:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>PDF</th>
<th style="text-align: right;">Pages</th>
<th style="text-align: right;">Wall (s/page)</th>
<th style="text-align: right;"><code>doc_enrich</code> (s/page)</th>
<th style="text-align: right;">doc_enrich / wall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>01_attention_is_all_you_need.pdf</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">50%</td>
</tr>
<tr class="even">
<td>02_mistral_7b.pdf</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">12%</td>
</tr>
<tr class="odd">
<td>03_mixtral_8x7b.pdf</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">37%</td>
</tr>
<tr class="even">
<td>04_qjl.pdf</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: right;"><strong>3.85</strong></td>
<td style="text-align: right;">80%</td>
</tr>
<tr class="odd">
<td>05_polarquant.pdf</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">8.72</td>
<td style="text-align: right;"><strong>7.97</strong></td>
<td style="text-align: right;">91%</td>
</tr>
<tr class="even">
<td>06_turboquant.pdf</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">6.36</td>
<td style="text-align: right;"><strong>5.39</strong></td>
<td style="text-align: right;">85%</td>
</tr>
<tr class="odd">
<td>07_deepseek_v4.pdf</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">62%</td>
</tr>
</tbody>
</table>
<p>A page of mistral costs 90 ms in <code>doc_enrich</code>. A page of polarquant costs 8 seconds. Two orders of magnitude. The reason is what the layout step finds on each page: very few formulas in the text-heavy papers, dozens of code and formula crops per page in the quantization papers. That spread is what makes a corpus-wide “where do I optimise” question deceptive: optimising the rendering backend would barely move polarquant, and optimising the formula VLM would barely move mistral. We attack the stage that dominates the documents that matter. For us, that’s the math-heavy papers, and that means the code and formula VLM is the first place to look.</p>
</section>
<section id="first-improvement-the-code-formula-model" class="level3">
<h3 class="anchored" data-anchor-id="first-improvement-the-code-formula-model">First improvement: the code &amp; formula model</h3>
<p><code>doc_enrich</code> is a per-region VLM inference. Every code block and every math formula the layout step detects gets cropped from the rendered page and sent through a vision-language model that emits the LaTeX (for formulas) or source text with a language tag (for code). On the math-heavy papers there can be dozens of these per page. The VLM is what the stage is.</p>
<section id="two-models-for-the-job" class="level4">
<h4 class="anchored" data-anchor-id="two-models-for-the-job">Two models for the job</h4>
<p>Two candidates exist for this slot. The default is <a href="https://huggingface.co/ibm-granite/granite-docling-258M">Granite-Docling-258M</a>, the same general-purpose document VLM that also powers Docling’s full-page VLM pipeline. The natural specialist is <a href="https://huggingface.co/docling-project/CodeFormulaV2">CodeFormulaV2</a>, purpose-built for crop-level transcription and trained on millions of code and formula images. They are similar in size (~300 M parameters). Docling’s <a href="https://docling-project.github.io/docling/usage/model_catalog/#inference-engines-by-model-family">model catalog</a> lists CodeFormulaV2 as the recommended option for the code/formula stage. The catch is in the same table: CodeFormulaV2’s supported inference engines are <strong>CPU / CUDA / XPU</strong>. There is no MLX entry.</p>
</section>
<section id="porting-codeformulav2-to-mlx" class="level4">
<h4 class="anchored" data-anchor-id="porting-codeformulav2-to-mlx">Porting CodeFormulaV2 to MLX</h4>
<p>CodeFormulaV2 is an <a href="https://huggingface.co/HuggingFaceM4/Idefics3-8B-Llama3">Idefics3</a> finetune, and Idefics3 is already a first-class architecture in <a href="https://github.com/Blaizzy/mlx-vlm">Blaizzy/mlx-vlm</a>. So the work is a weight conversion plus a small contribution that registers CodeFormulaV2 as a supported target of the existing <code>idefics3</code> runtime. Three quantised variants are published:</p>
<ul>
<li><a href="https://huggingface.co/mlx-community/CodeFormulaV2-mlx-bf16"><code>mlx-community/CodeFormulaV2-mlx-bf16</code></a></li>
<li><a href="https://huggingface.co/mlx-community/CodeFormulaV2-mlx-q8"><code>mlx-community/CodeFormulaV2-mlx-q8</code></a></li>
<li><a href="https://huggingface.co/mlx-community/CodeFormulaV2-mlx-q4"><code>mlx-community/CodeFormulaV2-mlx-q4</code></a></li>
</ul>
</section>
<section id="cpu-vs-mlx" class="level4">
<h4 class="anchored" data-anchor-id="cpu-vs-mlx">CPU vs MLX</h4>
<p>Three formula crops harvested from a page of <code>polarquant.pdf</code>, run through CodeFormulaV2 on both backends with greedy decode, identical inputs, two timed runs each:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Crop</th>
<th>Output</th>
<th style="text-align: right;">CPU torch (s)</th>
<th style="text-align: right;">MLX bf16 (s)</th>
<th style="text-align: right;">Speedup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>short formula</td>
<td>19 tokens</td>
<td style="text-align: right;">2.06 / 2.18</td>
<td style="text-align: right;">0.89 / 0.89</td>
<td style="text-align: right;">~2.3×</td>
</tr>
<tr class="even">
<td>medium formula</td>
<td>151 tokens</td>
<td style="text-align: right;">4.93 / 4.86</td>
<td style="text-align: right;">1.70 / 1.68</td>
<td style="text-align: right;">~2.9×</td>
</tr>
<tr class="odd">
<td>medium formula</td>
<td>124 tokens</td>
<td style="text-align: right;">4.30 / 4.29</td>
<td style="text-align: right;">1.55 / 1.52</td>
<td style="text-align: right;">~2.8×</td>
</tr>
<tr class="even">
<td><strong>median</strong></td>
<td></td>
<td style="text-align: right;"><strong>4.30</strong></td>
<td style="text-align: right;"><strong>1.54</strong></td>
<td style="text-align: right;"><strong>2.8×</strong></td>
</tr>
</tbody>
</table>
<p>Per crop, MLX is roughly 2.8× faster. The gap compounds across the math-heavy papers, where a single page can carry dozens of code and formula crops; across the full corpus on the MLX path, <code>doc_enrich</code> costs 269 seconds out of 329 seconds total wall.</p>
<p>Per-page <code>doc_enrich</code> cost on the math-heavy papers, MLX:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>PDF</th>
<th style="text-align: right;">Pages</th>
<th style="text-align: right;"><code>doc_enrich</code> (s/page)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>04_qjl.pdf</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">2.68</td>
</tr>
<tr class="even">
<td>05_polarquant.pdf</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">4.77</td>
</tr>
<tr class="odd">
<td>06_turboquant.pdf</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">2.65</td>
</tr>
<tr class="even">
<td>07_deepseek_v4.pdf</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">0.82</td>
</tr>
</tbody>
</table>
<p>The model the catalog actually recommends is now available to the laptop user, on the hardware the laptop has.</p>
</section>
</section>
<section id="second-improvement-the-layout-detector" class="level3">
<h3 class="anchored" data-anchor-id="second-improvement-the-layout-detector">Second improvement: the layout detector</h3>
<p>The <code>layout</code> stage uses <a href="https://huggingface.co/docling-project/docling-layout-heron"><code>docling-layout-heron</code></a>, an RT-DETRv2 object detector. Docling runs it on MPS through PyTorch. We ported RT-DETRv2 to MLX in <a href="https://github.com/Blaizzy/mlx-vlm/pull/1195">mlx-vlm PR #1195</a>, with the bf16 weights published at:</p>
<ul>
<li><a href="https://huggingface.co/mlx-community/docling-layout-heron-mlx-bf16"><code>mlx-community/docling-layout-heron-mlx-bf16</code></a></li>
<li><a href="https://huggingface.co/mlx-community/docling-layout-heron-101-mlx-bf16"><code>mlx-community/docling-layout-heron-101-mlx-bf16</code></a>.</li>
</ul>
<p>Full-corpus layout inference, 155 pages, median of 3 measured loops per PDF:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Backend</th>
<th style="text-align: right;">Corpus wall (s)</th>
<th style="text-align: right;">Per-page (s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PyTorch on MPS (Docling default)</td>
<td style="text-align: right;">39.20</td>
<td style="text-align: right;">0.253</td>
</tr>
<tr class="even">
<td><strong>MLX bf16 (this port)</strong></td>
<td style="text-align: right;"><strong>27.78</strong></td>
<td style="text-align: right;"><strong>0.179</strong></td>
</tr>
</tbody>
</table>
<p>About 1.4× faster on the same model, same corpus, same hardware. End-to-end, the layout stage is a small fraction of total wall (<code>doc_enrich</code> still dominates), so this iteration moves the corpus number by only a few seconds. The win is real but local; we keep it because the change is mechanical and the port lives in mlx-vlm anyway.</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>The two iterations together, CodeFormulaV2 on MLX for <code>doc_enrich</code> and RT-DETRv2 on MLX for <code>layout</code>, change the parsing budget on the same corpus, same hardware, same papers. Per-stage corpus totals (s), comparing the CPU path Docling’s catalog recommends (no MLX engine exists today for CodeFormulaV2 on Apple Silicon) to the same pipeline with our two ports plugged in:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th style="text-align: right;">CPU baseline</th>
<th style="text-align: right;">+ MLX ports (this work)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>page_parse</code></td>
<td style="text-align: right;">30.2</td>
<td style="text-align: right;">34.1</td>
</tr>
<tr class="even">
<td><code>layout</code></td>
<td style="text-align: right;">70.6</td>
<td style="text-align: right;"><strong>32.1</strong></td>
</tr>
<tr class="odd">
<td><code>doc_enrich</code></td>
<td style="text-align: right;"><strong>6 479.6</strong></td>
<td style="text-align: right;"><strong>260.5</strong></td>
</tr>
<tr class="even">
<td><code>doc_assemble</code></td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="odd">
<td><code>reading_order</code></td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.3</td>
</tr>
</tbody>
</table>
<p><code>doc_enrich</code> is the entire story: 6 480 s drops to 260 s, a 24.9× shrink on the stage that owns 99 % of the CPU baseline. The layout port adds a 2.2× speedup on its own stage. The other stages are unchanged Docling code.</p>
<p>Corpus-wide:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Pipeline configuration</th>
<th style="text-align: right;">Total wall</th>
<th style="text-align: right;">Per-page (s)</th>
<th style="text-align: right;">Speedup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CodeFormulaV2 on CPU (Docling catalog recommendation)</td>
<td style="text-align: right;"><strong>6 556 s</strong> (1 h 49 m)</td>
<td style="text-align: right;">42.3</td>
<td style="text-align: right;">1.0×</td>
</tr>
<tr class="even">
<td>CodeFormulaV2 MLX + RT-DETRv2 MLX (this work)</td>
<td style="text-align: right;"><strong>301 s</strong> (5 min)</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: right;"><strong>21.8×</strong></td>
</tr>
</tbody>
</table>
<p>From 1 h 49 m to 5 minutes on the same laptop, same papers, same model recommended by Docling’s catalog. What lands in Postgres at the end of it is the same <code>DoclingDocument</code> tree, with the same bounding boxes, ready for the next chapter: chunking and the embedder.</p>
</section>
</section>
<section id="the-embedding" class="level2">
<h2 class="anchored" data-anchor-id="the-embedding">The embedding</h2>
<p>The parser produces paragraph-anchored chunks. The embedder turns those chunks (and the user’s questions) into the vectors a similarity search will compare. The choice anchors everything downstream, so it is worth settling now, before we touch hybrid retrieval or reranking.</p>
<p>The usual framing is “pick the highest-scoring model on MTEB and move on”. For this project, three project-specific criteria sit above leaderboard position.</p>
<p><strong>Multilingual.</strong> The corpus is mostly English today, but the system should accept French papers and French questions without rebuilding the index. That rules out most of the small-and-fast end of the leaderboard.</p>
<p><strong>Sub-1B parameters.</strong> The pipeline already holds the parser, the layout detector, the formula VLM, and Qdrant resident. The embedder coexists with those on a 16 GB laptop. 7B and 8B models are out.</p>
<p><strong>Recall@k matters most at this stage.</strong> The retriever in this chapter is the first stage of a pipeline that will get a sparse-search leg (BM25 with RRF fusion) and a late-interaction reranker over the top-k. Both of those add precision back at the top of the ranking. What they cannot do is rescue a paragraph the dense retriever never returned. The metric to optimise here is <em>“did the relevant paragraph make it into the top-k candidate pool I will hand to the next stage?”</em> That is recall@k.</p>
<section id="the-candidates-models" class="level3">
<h3 class="anchored" data-anchor-id="the-candidates-models">The candidates models</h3>
<p>Four multilingual families, each in native precision (fp16 or bf16) and in 8-bit weight quantisation. All four run on Apple Silicon through <a href="https://github.com/Blaizzy/mlx-embeddings"><code>mlx-embeddings</code></a>. None of them required new MLX model code: the CLS-pooling dispatch we used to need a local patch for is <a href="https://github.com/Blaizzy/mlx-embeddings/pull/61">merged upstream</a> now.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Family</th>
<th style="text-align: right;">Params</th>
<th>Architecture</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://huggingface.co/BAAI/bge-m3">bge-m3</a></td>
<td style="text-align: right;">568 M</td>
<td>XLM-RoBERTa-large</td>
<td>100+ languages, CLS-pooled.</td>
</tr>
<tr class="even">
<td><a href="https://huggingface.co/Qwen/Qwen3-Embedding-0.6B">Qwen3-Embedding-0.6B</a></td>
<td style="text-align: right;">600 M</td>
<td>Qwen3 decoder</td>
<td>Last-token pooling, asymmetric (query prompt).</td>
</tr>
<tr class="odd">
<td><a href="https://huggingface.co/Qwen/Qwen3-Embedding-4B">Qwen3-Embedding-4B</a></td>
<td style="text-align: right;">4 000 M</td>
<td>Qwen3 decoder</td>
<td>Same family, 6.7× the parameters. Top of our size envelope.</td>
</tr>
<tr class="even">
<td><a href="https://huggingface.co/Snowflake/snowflake-arctic-embed-l-v2.0">snowflake-arctic-embed-l-v2.0</a></td>
<td style="text-align: right;">568 M</td>
<td>XLM-RoBERTa-large</td>
<td>74 languages, CLS-pooled.</td>
</tr>
</tbody>
</table>
</section>
<section id="dense-recallk" class="level3">
<h3 class="anchored" data-anchor-id="dense-recallk">Dense recall@k</h3>
<p>Benchmark: 581 questions, exact ANN search (brute-force cosine, no HNSW), the layout-anchored ground truth from earlier in the post, k=100 retrieved per question. Code: <a href="https://github.com/leonnoirclerc/rag/tree/main/eval"><code>eval/</code></a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="embedder_recall_dense.png" class="img-fluid figure-img"></p>
<figcaption>Dense recall@k for the four multilingual families, in fp16/bf16 and q8.</figcaption>
</figure>
</div>
<p><code>Snowflake-arctic-embed-l-v2.0</code> leads at every k from 3 to 100.<code>Qwen3-4B</code> sits 1-2 recall points below it through k=10 to k=50. <code>Qwen3-0.6B</code> and <code>bge-m3</code> are tied with each other and trail the leaders by 4-5 points at k=10. The q8 (dashed) lines track the full-precision ones within 0.5-1 recall point everywhere.</p>
<p>We chose to keep <code>Snowflake-arctic-embed-l-v2.0</code>.</p>
</section>
<section id="hybrid-retrieval" class="level3">
<h3 class="anchored" data-anchor-id="hybrid-retrieval">Hybrid retrieval</h3>
<p>Hybrid retrieval is the next chapter, but the embedder pick should hold up under both modes, so a preview is useful here.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="embedder_recall_hybrid.png" class="img-fluid figure-img"></p>
<figcaption>Dense vs hybrid recall@k, one panel per family. Hybrid = dense + Qdrant BM25, RRF-fused.</figcaption>
</figure>
</div>
<p>Recall@10 with the BM25 leg added:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>family</th>
<th style="text-align: right;">dense r@10</th>
<th style="text-align: right;">hybrid r@10</th>
<th style="text-align: right;">lift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bge-m3</td>
<td style="text-align: right;">72.5 %</td>
<td style="text-align: right;">76.5 %</td>
<td style="text-align: right;">+4.0</td>
</tr>
<tr class="even">
<td>Qwen3-0.6B</td>
<td style="text-align: right;">72.9 %</td>
<td style="text-align: right;">77.8 %</td>
<td style="text-align: right;">+4.9</td>
</tr>
<tr class="odd">
<td>Qwen3-4B</td>
<td style="text-align: right;">75.4 %</td>
<td style="text-align: right;">77.7 %</td>
<td style="text-align: right;">+2.3</td>
</tr>
<tr class="even">
<td>snowflake-arctic-l-v2</td>
<td style="text-align: right;">76.5 %</td>
<td style="text-align: right;">78.9 %</td>
<td style="text-align: right;">+2.4</td>
</tr>
</tbody>
</table>
<p>Hybrid lifts every family, and lifts the weaker dense retrievers more. The rank order across families is unchanged after fusion. The embedder choice is robust to retrieval mode.</p>
<p>We keep <code>Snowflake-arctic-embed-l-v2.0</code> with BM25 hybrid search</p>
</section>
<section id="quantization" class="level3">
<h3 class="anchored" data-anchor-id="quantization">Quantization</h3>
<p>A 568 M model in bf16 is 1.1 GB on disk. The q8 version is 576 MB. On a 16 GB machine where the pipeline already holds the rest of the pipeline, halving the embedder’s memory footprint is real headroom.</p>
<p>The recall cost at k=10 is at most 0.7 points across the four families, and closes to nothing by k=50. Quality-wise, q8 is free.</p>
<p>We chose <code>Snowflake-arctic-embed-l-v2.0</code> quantized to 8 bits with BM25 hybrid search.</p>
</section>
<section id="indexing-speed" class="level3">
<h3 class="anchored" data-anchor-id="indexing-speed">Indexing speed</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="embedder_speed_vs_recall.png" class="img-fluid figure-img"></p>
<figcaption>Indexing throughput vs dense recall@10. Top-right wins.</figcaption>
</figure>
</div>
<p>The 568 M and 600 M models index in well under a minute for the 581-paragraph corpus (800-3000 tokens/second, depending on family and precision). <code>Qwen3-4B</code> is roughly 10× slower (~180 tokens/second; about six minutes to re-index the corpus). At the 100k-paragraph scale a real-world corpus would have, that is the difference between an embed step that takes a few minutes and one that takes an hour.</p>
<p>q8 is not uniformly faster than full precision on MLX. It is faster for <code>Snowflake</code> (1.1×), slightly slower for <code>bge-m3</code> and <code>Qwen3-4B</code>, and noticeably slower for<code>Qwen3-0.6B</code> (2.5× slower). The gap depends on which architecture has a fully-vectorised dequantisation path in <code>mlx-embeddings</code> at this version, and is the kind of thing that closes upstream as more families get tuned. For now: treat q8 as a memory and disk win, not a speed win.</p>
<p>The cleanest Pareto point on the chart is <code>snowflake-arctic-l-v2 q8</code>: best recall@10 of any sub-1B variant, fastest throughput of any sub-1B variant.</p>
</section>
<section id="the-pick" class="level3">
<h3 class="anchored" data-anchor-id="the-pick">The pick</h3>
<p><strong>snowflake-arctic-embed-l-v2.0, q8.</strong> Tops dense recall at every k tested, tops hybrid recall too, shares the 568 M size class with <code>bge-m3</code>, and the q8 quantisation gives us a 576 MB on-disk footprint with no big quality cost.</p>
</section>
</section>
<section id="reranking" class="level2">
<h2 class="anchored" data-anchor-id="reranking">Reranking</h2>
<p>The next logical step after hybrid retrieval is <strong>reranking</strong>: take the top-K candidates from the prefetch and re-score them with a more expensive but more accurate model. The usual reranker family is the cross-encoder. One model, taking a (query, document) pair, emits a relevance score. The catch is cost. A cross-encoder makes one full forward pass per candidate, and competitive multilingual cross-encoders are 500M+ parameters. With top-K=50, that is 50 forwards through a heavy model per query. Our latency budget is sub-second total; a cross-encoder rerank alone would blow that.</p>
<p><strong>Late-interaction (ColBERT-style) reranking</strong> offers a different trade-off. Each document is encoded once into a sequence of per-token vectors at index time and stored on disk. At query time, the query is encoded the same way, and the score is a cheap MaxSim aggregation over per-token similarities. The work the cross-encoder pays per-pair at query time is amortised at index time, paid once per document. The model size is similar but the per-query cost drops from “K model forwards” to “1 model forward + K small dot-product reductions”. That shape fits the latency budget. It is also why we already configured the late-interaction multi-vector field in Qdrant earlier in the post.</p>
<section id="the-multilingual-options" class="level3">
<h3 class="anchored" data-anchor-id="the-multilingual-options">The multilingual options</h3>
<p>We considered two multilingual late-interaction models:</p>
<ul>
<li><a href="https://huggingface.co/jinaai/jina-colbert-v2"><code>jinaai/jina-colbert-v2</code></a>: 559 M parameters, 94 languages, 128-dim per-token vectors.</li>
<li><a href="https://huggingface.co/BAAI/bge-m3">BAAI/bge-m3 multivector head</a>: the same bge-m3 we already load for dense, with its multi-vector head applied to per-token outputs. 1024-dim per token, eight times the storage and the MaxSim compute of jina. It is not Matryoshka-trained, so naively truncating to a comparable 128-d would discard most of the signal in unprincipled ways.</li>
</ul>
<p>We picked <strong>jina-colbert-v2</strong>: native low dim, training designed for the task, and the multilingual coverage is strictly broader than bge-m3’s.</p>
<p>We ported jina-colbert-v2 to MLX (<a href="https://github.com/leonnoirclerc/rag/blob/main/src/rag/embedding/colbert.py"><code>src/rag/embedding/colbert.py</code></a>) on top of the same <code>xlm-roberta-rope</code> backbone we vendored from mlx-vlm. Storage trick: the multi-vector field in Qdrant has HNSW disabled (<code>hnsw_config.m=0</code>) and lives on disk. It is only ever scored exact-MaxSim against the candidates the prefetch returns, so building a graph would be wasted work.</p>
</section>
<section id="hit1-across-the-four-multilingual-families" class="level3">
<h3 class="anchored" data-anchor-id="hit1-across-the-four-multilingual-families">Hit@1 across the four multilingual families</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="late_interaction_hit1.png" class="img-fluid figure-img"></p>
<figcaption>Top-1 precision under dense, +BM25 hybrid, +ColBERT MaxSim rerank (jina-colbert-v2), and both stacked. The reranker here is jina-colbert-v2 in every case. Hybrid (light) is the best column for three of four families.</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>family</th>
<th style="text-align: right;">dense</th>
<th style="text-align: right;">hybrid</th>
<th style="text-align: right;">+colbert</th>
<th style="text-align: right;">hybrid+colbert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>snowflake-l-v2</td>
<td style="text-align: right;">67.5</td>
<td style="text-align: right;"><strong>76.1</strong></td>
<td style="text-align: right;">73.1</td>
<td style="text-align: right;">73.1</td>
</tr>
<tr class="even">
<td>Qwen3-4B</td>
<td style="text-align: right;">68.7</td>
<td style="text-align: right;"><strong>74.5</strong></td>
<td style="text-align: right;">72.5</td>
<td style="text-align: right;">73.1</td>
</tr>
<tr class="odd">
<td>Qwen3-0.6B</td>
<td style="text-align: right;">70.6</td>
<td style="text-align: right;"><strong>75.4</strong></td>
<td style="text-align: right;">72.8</td>
<td style="text-align: right;">72.8</td>
</tr>
<tr class="even">
<td>bge-m3</td>
<td style="text-align: right;">68.5</td>
<td style="text-align: right;">72.3</td>
<td style="text-align: right;"><strong>73.1</strong></td>
<td style="text-align: right;">73.1</td>
</tr>
</tbody>
</table>
<p><strong>jina-colbert-v2 does not improve our retrieval.</strong> Hybrid alone wins on three of four families. The one family where ColBERT helps (bge-m3) gains less than a point. Stacking ColBERT on top of hybrid ties “+ColBERT alone” in every family, which means the BM25 leg surfaces candidates that ColBERT then deranks back. The two scoring systems are not stacking; they are trading.</p>
<p>The full metric table on snowflake-l-v2 (our picked embedder):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>variant</th>
<th style="text-align: right;">hit@1</th>
<th style="text-align: right;">hit@5</th>
<th style="text-align: right;">hit@10</th>
<th style="text-align: right;">recall@10</th>
<th style="text-align: right;">mrr</th>
<th style="text-align: right;">ndcg@10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>hybrid (no rerank)</td>
<td style="text-align: right;"><strong>73.8</strong></td>
<td style="text-align: right;"><strong>92.5</strong></td>
<td style="text-align: right;"><strong>96.2</strong></td>
<td style="text-align: right;"><strong>78.9</strong></td>
<td style="text-align: right;"><strong>82.1</strong></td>
<td style="text-align: right;"><strong>71.6</strong></td>
</tr>
<tr class="even">
<td>hybrid + ColBERT</td>
<td style="text-align: right;">73.1</td>
<td style="text-align: right;">91.9</td>
<td style="text-align: right;">95.4</td>
<td style="text-align: right;">76.3</td>
<td style="text-align: right;">81.4</td>
<td style="text-align: right;">69.8</td>
</tr>
</tbody>
</table>
<p>Two failure examples make the mechanism concrete. Both are queries where snowflake-hybrid had the right paragraph at rank 1 and ColBERT then demoted it.</p>
<blockquote class="blockquote">
<p><strong>Q:</strong> <em>“What two-stage process does DeepSeek-V4-Flash follow when introducing sparse attention during training, and at what sequence length and token count is sparsity first activated?”</em></p>
<p><strong>Hybrid rank 1 (correct):</strong> the training-recipe paragraph with the sparsity schedule and the token-count cutoffs.</p>
<p><strong>ColBERT rank 1 (wrong):</strong> the paper’s abstract, which mentions “DeepSeek-V4-Flash”, “sparse attention”, and “training” multiple times but does not answer the specific question.</p>
<p>Right answer demoted to rank 16.</p>
<p><strong>Why ColBERT failed here.</strong> The abstract has many tokens that match the query’s topic words. MaxSim sums those matches, so the abstract scores high. The specific training paragraph mentions the same topic words fewer times and loses on token count, even though it actually contains the answer.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Q:</strong> <em>“How are the authors of the DeepSeek-V4 paper listed, and what does the asterisk (</em>) notation next to certain author names indicate?“*</p>
<p><strong>Hybrid rank 1 (correct):</strong> the two-sentence answer, exactly: <em>“Authors are listed alphabetically by their first name. Names marked with * denote individuals who have departed from our team.”</em></p>
<p><strong>ColBERT rank 1 (wrong):</strong> an unrelated paragraph about Mixture-of-Experts architecture that happens to mention “DeepSeek-V4”.</p>
<p>Right answer demoted to rank 8.</p>
<p><strong>Why ColBERT failed here.</strong> The right answer is short, about 25 tokens. MaxSim’s score scales with the number of high-similarity doc tokens, so short answers are systematically under-scored. The long MoE paragraph wins on token count.</p>
</blockquote>
<p>The pattern across the 41 cases where ColBERT demoted the right answer is consistent: it rewards token-rich generic content; BM25’s IDF weighting rewards rare-word matches that pinpoint specific answers. On a corpus of short technical paragraphs answering specific questions, hybrid retrieval is the right tool. ColBERT was built for a different corpus shape.</p>
</section>
<section id="what-we-ship" class="level3">
<h3 class="anchored" data-anchor-id="what-we-ship">What we ship</h3>
<p>The retrieval pipeline stops at <strong>dense + BM25 with RRF fusion</strong>. ColBERT MaxSim does not earn its keep on this corpus, and stacking it on top of hybrid does not help in any family. We keep the MLX <code>jina-colbert-v2</code> port in the codebase as a documented building block. If the corpus later shifts to long documents or to an out-of-domain mix, this is the obvious next thing to revisit.</p>
<hr>
<p><strong>Code state at time of writing:</strong> <a href="https://github.com/leonnoirclerc/rag/commit/d72e8993f047c6b559062edfb7e5156299e8f33c"><code>d72e899</code></a>. <strong>Reproduce the parsing numbers:</strong> <code>uv run python -m benchmark.pdf_pipeline --variants codeformulav2_mlx</code>. <strong>Reproduce the embedder + late-interaction sweeps:</strong> <code>uv run python -m eval.sweep</code>.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/leonnoirclerc\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "A grounded RAG system, on a laptop"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Building a grounded, fast, efficient RAG system from scratch on a 16 GB MacBook. This post grows as the system grows: each new iteration on the pipeline lands as a new subsection with the numbers behind it."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-18"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> "2026-05-20"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [rag-laptop]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> pipeline.svg</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>This is a post about building a grounded RAG system from scratch. The</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>goal is simple to state: point it at a stack of PDFs, ask a question</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>in natural language, get back an answer together with the exact</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>bounding box on the exact page that answer came from. The constraint</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>is what makes it interesting. The whole thing has to run on the laptop</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>I'm writing on, a MacBook Pro M2 with 16 GB of unified memory, no</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>cloud GPU.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="al">![The main constraint: we are GPU poor :( ](gpu_poor.png)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>The post starts from the simplest version of the pipeline that hits</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>the goal, then iterates from there. Each iteration is its own</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>subsection, with the reasoning, the numbers, and a link to whatever</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>code or model weights came out of it.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Grounded, Fast, Efficient</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>Three goals, easy to state.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>**Grounded.** Every answer has to point back to the bounding box on</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>the page it came from. Not a citation in plain text, a visible region</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>on the rendered page, one you can click on and verify.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>**Fast.** Sub-second retrieval on a single query. Anything slower</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>turns iteration into a chore, and this is a system meant to be</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>iterated on a lot.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Efficient.** Fits in 16 GB. Runs alongside a browser, an editor,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>and the Docker stack the system itself depends on. No cloud GPU, no</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>API key billed by the token. The whole thing needs to be self-contained</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>enough that someone could clone the repo and have it work.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="fu">## The stack</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Anything we want to retrieve later, we have to store first. The</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>system has three layers underneath: the binary files that come in,</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>the structured representation we extract from them, and the vector</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>index we build on top to make them searchable.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>**Document storage.** PDFs land in a blob store keyed by a UUID.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Local case is just a directory; behind a thin</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">fsspec</span><span class="co">](https://github.com/fsspec/filesystem_spec)</span> wrapper so the</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>day this needs to live in S3 instead, the change is a config swap.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>**The structured database.** A document has pages, each page has</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>layout elements (paragraphs, headings, tables, figures, formulas,</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>code blocks), and each element has one or more bounding boxes. That</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>hierarchy lives in <span class="co">[</span><span class="ot">Postgres</span><span class="co">](https://www.postgresql.org/)</span> via</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">SQLAlchemy</span><span class="co">](https://www.sqlalchemy.org/)</span>. On top of the elements</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>come **chunks**, the unit the embedder sees and retrieval returns.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>Each chunk keeps a link back to the elements it covers, so a hit can</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>be traced to specific page regions.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>**The vector store.** One vector per chunk, in</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Qdrant</span><span class="co">](https://qdrant.tech/)</span>, keyed by chunk UUID, with a small</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>payload (just the parent document id, for filtering). Everything else</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>stays in Postgres.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>**The embedder.** Starting point is</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">bge-m3</span><span class="co">](https://huggingface.co/BAAI/bge-m3)</span>: 1024-dimensional</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>vectors, ~1.1 GB resident at fp16 on Apple Silicon, a defensible</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>default for general-purpose retrieval.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="al">![Pipeline overview: blob storage, Postgres with the document, page, and element hierarchy, and the vector database side by side.](pipeline.svg)</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>The parser is where the real work begins, and that's where the rest</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>of this post lives.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## The parsing</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Docling</span><span class="co">](https://github.com/docling-project/docling)</span> is the tool we</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>use to turn a PDF into a structured tree. That tree is the input to</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>everything that follows: chunking, embedding, retrieval, grounding.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>It controls what each later stage can see. So before we build any of</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>that on top, we should know how the parsing actually behaves on our</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>corpus, what it costs, and whether the defaults are the right ones.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### Two routes Docling offers</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Docling exposes two top-level ways to turn a page into structured</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>content.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>The first is the **traditional pipeline**: a layered stack of small</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>specialist models running in sequence. A CNN layout detector finds</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>text blocks, tables, pictures, formulas, and code. A separate model</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>parses table structure into rows and columns. A small</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>vision-language model runs on cropped code and formula regions to</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>turn them into LaTeX or source text. A figure classifier labels</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>pictures by type. The text inside each block comes from the PDF's</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>own text layer, extracted by a dedicated parser. Each stage has one</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>job, runs on one slice of the page, and produces one piece of the</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>final document.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>The second is the **VLM pipeline**: one large vision-language model</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>gets the rendered page image and emits the entire structured</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>document for that page in one shot. No separate layout step. No</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>separate table parsing. The model decides where the text blocks are,</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>where the tables are, what the cells contain, which regions are</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>pictures, all at once. The Docling-blessed model for this path is</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Granite-Docling-258M</span><span class="co">](https://huggingface.co/ibm-granite/granite-docling-258M)</span>,</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>available as an MLX export for Apple Silicon.</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>Both routes produce a structurally similar <span class="in">`DoclingDocument`</span>, and</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>Docling lets us swap between them by changing a single configuration</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>object.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="fu">### What each route costs on our corpus</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>Seven research papers, 155 pages total. Each variant runs each PDF</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>once untimed (warmup) then three times measured; we report the</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>median wall time per variant per doc, summed across the corpus. All</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>on Apple Silicon. Code:</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`benchmark/pdf_pipeline/`</span><span class="co">](https://github.com/leonnoirclerc/rag/tree/d72e8993f047c6b559062edfb7e5156299e8f33c/benchmark/pdf_pipeline)</span>.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variant <span class="pp">|</span> Total wall (s) <span class="pp">|</span> Per-page (s) <span class="pp">|</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> traditional <span class="pp">|</span> 582.4 <span class="pp">|</span> 3.8 <span class="pp">|</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> VLM (Granite-Docling-258M MLX) <span class="pp">|</span> ~2 000 <span class="pp">|</span> ~13 <span class="pp">|</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>Roughly one order of magnitude. The traditional pipeline does cheap</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>text extraction on the bulk of the page (the prose, where the PDF</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>already has a clean text layer) and saves the expensive VLM passes</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>for the few regions that genuinely need them: the cropped code and</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>formula boxes. The VLM pipeline pays the full VLM cost on every page</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>to re-derive content that is already sitting in the PDF text stream.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>For our corpus, which is born-digital papers with clean text layers,</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>the traditional pipeline is the right trade.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inside the traditional pipeline</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>The traditional pipeline is a pipeline in the literal sense: pages</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>stream through ordered stages, with multiple pages in different</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>stages at once. Each stage owns one piece of the page-to-document</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>translation, and each one is a place we can attack independently.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Stage <span class="pp">|</span> What it does <span class="pp">|</span> Implementation <span class="pp">|</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`page_parse`</span> <span class="pp">|</span> Render the page to an image at two scales, extract text cells with bboxes from the PDF text layer <span class="pp">|</span> pypdfium2 (C++) for rendering, <span class="co">[</span><span class="ot">docling-parse</span><span class="co">](https://github.com/docling-project/docling-parse)</span> (C++) for text extraction <span class="pp">|</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`layout`</span> <span class="pp">|</span> Detect text blocks, tables, pictures, formulas, code regions on the rendered page <span class="pp">|</span> Object-detection CNN running on MPS <span class="pp">|</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`table_structure`</span> <span class="pp">|</span> Parse the cell grid of each detected table <span class="pp">|</span> TableFormer V1, CPU on Apple Silicon <span class="pp">|</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`doc_enrich`</span> <span class="pp">|</span> Crop each detected code or formula region and run a VLM on it to get LaTeX or source <span class="pp">|</span> Granite-Docling-258M, MLX <span class="pp">|</span></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`reading_order`</span> <span class="pp">|</span> Decide the order in which elements appear in the final document <span class="pp">|</span> CPU heuristics <span class="pp">|</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`doc_assemble`</span> <span class="pp">|</span> Build the final <span class="in">`DoclingDocument`</span> tree <span class="pp">|</span> Pure Python <span class="pp">|</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>Picture classification piggybacks on <span class="in">`doc_enrich`</span>. Tables are a</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>stage of their own. Code and math sit inside <span class="in">`doc_enrich`</span> because</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>they share the same VLM and the same per-region inference path.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### Where is the bottleneck?</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>Per-page wall time across the corpus, with tables on:</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Stage <span class="pp">|</span> Per-page wall (ms) <span class="pp">|</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`page_parse`</span> <span class="pp">|</span> 500 <span class="pp">|</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`layout`</span> <span class="pp">|</span> 497 <span class="pp">|</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`table_structure`</span> <span class="pp">|</span> 544 <span class="pp">|</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`doc_enrich`</span> <span class="pp">|</span> **2 936** <span class="pp">|</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="in">`doc_enrich`</span> dominates the average. But the average hides the most</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>useful fact: the bottleneck depends on the document. Per-page wall</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>time, split per paper:</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PDF <span class="pp">|</span> Pages <span class="pp">|</span> Wall (s/page) <span class="pp">|</span> <span class="in">`doc_enrich`</span> (s/page) <span class="pp">|</span> doc_enrich / wall <span class="pp">|</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 01_attention_is_all_you_need.pdf <span class="pp">|</span> 15 <span class="pp">|</span> 1.27 <span class="pp">|</span> 0.63 <span class="pp">|</span> 50% <span class="pp">|</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 02_mistral_7b.pdf <span class="pp">|</span> 9 <span class="pp">|</span> 0.79 <span class="pp">|</span> 0.09 <span class="pp">|</span> 12% <span class="pp">|</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 03_mixtral_8x7b.pdf <span class="pp">|</span> 13 <span class="pp">|</span> 1.42 <span class="pp">|</span> 0.52 <span class="pp">|</span> 37% <span class="pp">|</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 04_qjl.pdf <span class="pp">|</span> 13 <span class="pp">|</span> 4.81 <span class="pp">|</span> **3.85** <span class="pp">|</span> 80% <span class="pp">|</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 05_polarquant.pdf <span class="pp">|</span> 22 <span class="pp">|</span> 8.72 <span class="pp">|</span> **7.97** <span class="pp">|</span> 91% <span class="pp">|</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 06_turboquant.pdf <span class="pp">|</span> 25 <span class="pp">|</span> 6.36 <span class="pp">|</span> **5.39** <span class="pp">|</span> 85% <span class="pp">|</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 07_deepseek_v4.pdf <span class="pp">|</span> 58 <span class="pp">|</span> 2.15 <span class="pp">|</span> 1.34 <span class="pp">|</span> 62% <span class="pp">|</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>A page of mistral costs 90 ms in <span class="in">`doc_enrich`</span>. A page of polarquant</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>costs 8 seconds. Two orders of magnitude. The reason is what the</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>layout step finds on each page: very few formulas in the text-heavy</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>papers, dozens of code and formula crops per page in the</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>quantization papers. That spread is what makes a corpus-wide "where</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>do I optimise" question deceptive: optimising the rendering backend</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>would barely move polarquant, and optimising the formula VLM would</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>barely move mistral. We attack the stage that dominates the</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>documents that matter. For us, that's the math-heavy papers, and</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>that means the code and formula VLM is the first place to look.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="fu">### First improvement: the code &amp; formula model</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="in">`doc_enrich`</span> is a per-region VLM inference. Every code block and</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>every math formula the layout step detects gets cropped from the</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>rendered page and sent through a vision-language model that emits</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>the LaTeX (for formulas) or source text with a language tag (for</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>code). On the math-heavy papers there can be dozens of these per</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>page. The VLM is what the stage is.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Two models for the job</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>Two candidates exist for this slot. The default is</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Granite-Docling-258M</span><span class="co">](https://huggingface.co/ibm-granite/granite-docling-258M)</span>,</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>the same general-purpose document VLM that also powers Docling's</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>full-page VLM pipeline. The natural specialist is</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">CodeFormulaV2</span><span class="co">](https://huggingface.co/docling-project/CodeFormulaV2)</span>,</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>purpose-built for crop-level transcription and trained on millions</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>of code and formula images. They are similar in size (~300 M</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>parameters). Docling's</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">model catalog</span><span class="co">](https://docling-project.github.io/docling/usage/model_catalog/#inference-engines-by-model-family)</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>lists CodeFormulaV2 as the recommended option for the code/formula</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>stage. The catch is in the same table: CodeFormulaV2's supported</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>inference engines are **CPU / CUDA / XPU**. There is no MLX entry.</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Porting CodeFormulaV2 to MLX</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>CodeFormulaV2 is an</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Idefics3</span><span class="co">](https://huggingface.co/HuggingFaceM4/Idefics3-8B-Llama3)</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>finetune, and Idefics3 is already a first-class architecture in</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Blaizzy/mlx-vlm</span><span class="co">](https://github.com/Blaizzy/mlx-vlm)</span>. So the work</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>is a weight conversion plus a small contribution that registers</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>CodeFormulaV2 as a supported target of the existing <span class="in">`idefics3`</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>runtime. Three quantised variants are published:</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`mlx-community/CodeFormulaV2-mlx-bf16`</span><span class="co">](https://huggingface.co/mlx-community/CodeFormulaV2-mlx-bf16)</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`mlx-community/CodeFormulaV2-mlx-q8`</span><span class="co">](https://huggingface.co/mlx-community/CodeFormulaV2-mlx-q8)</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`mlx-community/CodeFormulaV2-mlx-q4`</span><span class="co">](https://huggingface.co/mlx-community/CodeFormulaV2-mlx-q4)</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="fu">#### CPU vs MLX</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>Three formula crops harvested from a page of <span class="in">`polarquant.pdf`</span>, run</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>through CodeFormulaV2 on both backends with greedy decode, identical</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>inputs, two timed runs each:</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Crop <span class="pp">|</span> Output <span class="pp">|</span> CPU torch (s) <span class="pp">|</span> MLX bf16 (s) <span class="pp">|</span> Speedup <span class="pp">|</span></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---:|---:|</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> short formula <span class="pp">|</span> 19 tokens <span class="pp">|</span> 2.06 / 2.18 <span class="pp">|</span> 0.89 / 0.89 <span class="pp">|</span> ~2.3× <span class="pp">|</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> medium formula <span class="pp">|</span> 151 tokens <span class="pp">|</span> 4.93 / 4.86 <span class="pp">|</span> 1.70 / 1.68 <span class="pp">|</span> ~2.9× <span class="pp">|</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> medium formula <span class="pp">|</span> 124 tokens <span class="pp">|</span> 4.30 / 4.29 <span class="pp">|</span> 1.55 / 1.52 <span class="pp">|</span> ~2.8× <span class="pp">|</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **median** |  | **4.30** | **1.54** | **2.8×** <span class="pp">|</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>Per crop, MLX is roughly 2.8× faster. The gap compounds across the</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>math-heavy papers, where a single page can carry dozens of code and</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>formula crops; across the full corpus on the MLX path, <span class="in">`doc_enrich`</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>costs 269 seconds out of 329 seconds total wall.</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>Per-page <span class="in">`doc_enrich`</span> cost on the math-heavy papers, MLX:</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PDF <span class="pp">|</span> Pages <span class="pp">|</span> <span class="in">`doc_enrich`</span> (s/page) <span class="pp">|</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 04_qjl.pdf <span class="pp">|</span> 13 <span class="pp">|</span> 2.68 <span class="pp">|</span></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 05_polarquant.pdf <span class="pp">|</span> 22 <span class="pp">|</span> 4.77 <span class="pp">|</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 06_turboquant.pdf <span class="pp">|</span> 25 <span class="pp">|</span> 2.65 <span class="pp">|</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 07_deepseek_v4.pdf <span class="pp">|</span> 58 <span class="pp">|</span> 0.82 <span class="pp">|</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>The model the catalog actually recommends is now available to the</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>laptop user, on the hardware the laptop has.</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="fu">### Second improvement: the layout detector</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>The <span class="in">`layout`</span> stage uses</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`docling-layout-heron`</span><span class="co">](https://huggingface.co/docling-project/docling-layout-heron)</span>,</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>an RT-DETRv2 object detector. Docling runs it on MPS through</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>PyTorch. We ported RT-DETRv2 to MLX in</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">mlx-vlm PR #1195</span><span class="co">](https://github.com/Blaizzy/mlx-vlm/pull/1195)</span>, with</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>the bf16 weights published at:</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`mlx-community/docling-layout-heron-mlx-bf16`</span><span class="co">](https://huggingface.co/mlx-community/docling-layout-heron-mlx-bf16)</span></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`mlx-community/docling-layout-heron-101-mlx-bf16`</span><span class="co">](https://huggingface.co/mlx-community/docling-layout-heron-101-mlx-bf16)</span>.</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>Full-corpus layout inference, 155 pages, median of 3 measured loops</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>per PDF:</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Backend <span class="pp">|</span> Corpus wall (s) <span class="pp">|</span> Per-page (s) <span class="pp">|</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PyTorch on MPS (Docling default) <span class="pp">|</span> 39.20 <span class="pp">|</span> 0.253 <span class="pp">|</span></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **MLX bf16 (this port)** | **27.78** | **0.179** <span class="pp">|</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>About 1.4× faster on the same model, same corpus, same hardware.</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>End-to-end, the layout stage is a small fraction of total wall</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>(<span class="in">`doc_enrich`</span> still dominates), so this iteration moves the corpus</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>number by only a few seconds. The win is real but local; we keep it</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>because the change is mechanical and the port lives in mlx-vlm anyway.</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Results</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>The two iterations together, CodeFormulaV2 on MLX for <span class="in">`doc_enrich`</span> and</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>RT-DETRv2 on MLX for <span class="in">`layout`</span>, change the parsing budget on the same</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>corpus, same hardware, same papers. Per-stage corpus totals (s),</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>comparing the CPU path Docling's catalog recommends (no MLX engine</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>exists today for CodeFormulaV2 on Apple Silicon) to the same pipeline</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>with our two ports plugged in:</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Stage <span class="pp">|</span> CPU baseline <span class="pp">|</span> + MLX ports (this work) <span class="pp">|</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`page_parse`</span> <span class="pp">|</span> 30.2 <span class="pp">|</span> 34.1 <span class="pp">|</span></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`layout`</span> <span class="pp">|</span> 70.6 <span class="pp">|</span> **32.1** <span class="pp">|</span></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`doc_enrich`</span> <span class="pp">|</span> **6 479.6** | **260.5** <span class="pp">|</span></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`doc_assemble`</span> <span class="pp">|</span> 1.0 <span class="pp">|</span> 0.7 <span class="pp">|</span></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`reading_order`</span> <span class="pp">|</span> 0.6 <span class="pp">|</span> 0.3 <span class="pp">|</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="in">`doc_enrich`</span> is the entire story: 6 480 s drops to 260 s, a 24.9×</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>shrink on the stage that owns 99 % of the CPU baseline. The layout</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>port adds a 2.2× speedup on its own stage. The other stages are</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>unchanged Docling code.</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>Corpus-wide:</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pipeline configuration <span class="pp">|</span> Total wall <span class="pp">|</span> Per-page (s) <span class="pp">|</span> Speedup <span class="pp">|</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CodeFormulaV2 on CPU (Docling catalog recommendation) <span class="pp">|</span> **6 556 s** (1 h 49 m) <span class="pp">|</span> 42.3 <span class="pp">|</span> 1.0× <span class="pp">|</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CodeFormulaV2 MLX + RT-DETRv2 MLX (this work) <span class="pp">|</span> **301 s** (5 min) | 1.94 | **21.8×** <span class="pp">|</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>From 1 h 49 m to 5 minutes on the same laptop, same papers, same</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>model recommended by Docling's catalog. What lands in Postgres at the</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>end of it is the same <span class="in">`DoclingDocument`</span> tree, with the same bounding</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>boxes, ready for the next chapter: chunking and the embedder.</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="fu">## The embedding</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>The parser produces paragraph-anchored chunks. The embedder turns those</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>chunks (and the user's questions) into the vectors a similarity search</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>will compare. The choice anchors everything downstream, so it is worth</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>settling now, before we touch hybrid retrieval or reranking.</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>The usual framing is "pick the highest-scoring model on MTEB and move on".</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>For this project, three project-specific criteria sit above leaderboard</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>position.</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>**Multilingual.** The corpus is mostly English today, but the system</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>should accept French papers and French questions without rebuilding the</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>index. That rules out most of the small-and-fast end of the leaderboard.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>**Sub-1B parameters.** The pipeline already</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a>holds the parser, the layout detector, the formula VLM, and Qdrant</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>resident. The embedder coexists with those on a 16 GB laptop. 7B and 8B</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a>models are out.</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a>**Recall@k matters most at this stage.** The</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>retriever in this chapter is the first stage of a pipeline that will get</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>a sparse-search leg (BM25 with RRF fusion) and a late-interaction</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>reranker over the top-k. Both of those add precision back at the top of</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>the ranking. What they cannot do is rescue a paragraph the dense</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>retriever never returned. The metric to optimise here is *"did the</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>relevant paragraph make it into the top-k candidate pool I will hand to</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>the next stage?"* That is recall@k.</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a><span class="fu">### The candidates models</span></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>Four multilingual families, each in native precision (fp16 or bf16) and</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>in 8-bit weight quantisation. All four run on Apple Silicon through</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`mlx-embeddings`</span><span class="co">](https://github.com/Blaizzy/mlx-embeddings)</span>. None of</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>them required new MLX model code: the CLS-pooling dispatch we used</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>to need a local patch for is</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">merged upstream</span><span class="co">](https://github.com/Blaizzy/mlx-embeddings/pull/61)</span></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>now.</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Family <span class="pp">|</span> Params <span class="pp">|</span> Architecture <span class="pp">|</span> Notes <span class="pp">|</span></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---|---|</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">bge-m3</span><span class="co">](https://huggingface.co/BAAI/bge-m3)</span> <span class="pp">|</span> 568 M <span class="pp">|</span> XLM-RoBERTa-large <span class="pp">|</span> 100+ languages, CLS-pooled. <span class="pp">|</span></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Qwen3-Embedding-0.6B</span><span class="co">](https://huggingface.co/Qwen/Qwen3-Embedding-0.6B)</span> <span class="pp">|</span> 600 M <span class="pp">|</span> Qwen3 decoder <span class="pp">|</span> Last-token pooling, asymmetric (query prompt). <span class="pp">|</span></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">Qwen3-Embedding-4B</span><span class="co">](https://huggingface.co/Qwen/Qwen3-Embedding-4B)</span> <span class="pp">|</span> 4 000 M <span class="pp">|</span> Qwen3 decoder <span class="pp">|</span> Same family, 6.7× the parameters. Top of our size envelope. <span class="pp">|</span></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">snowflake-arctic-embed-l-v2.0</span><span class="co">](https://huggingface.co/Snowflake/snowflake-arctic-embed-l-v2.0)</span> <span class="pp">|</span> 568 M <span class="pp">|</span> XLM-RoBERTa-large <span class="pp">|</span> 74 languages, CLS-pooled. <span class="pp">|</span></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="fu">### Dense recall@k</span></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>Benchmark: 581 questions, exact ANN search (brute-force cosine, no HNSW), the layout-anchored ground truth from earlier in the post,</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>k=100 retrieved per question. Code:</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`eval/`</span><span class="co">](https://github.com/leonnoirclerc/rag/tree/main/eval)</span>.</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a><span class="al">![Dense recall@k for the four multilingual families, in fp16/bf16 and q8.](embedder_recall_dense.png)</span></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a><span class="in">`Snowflake-arctic-embed-l-v2.0`</span> leads at every k from 3 to 100.<span class="in">`Qwen3-4B`</span></span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>sits 1-2 recall points below it through k=10 to k=50. <span class="in">`Qwen3-0.6B`</span> and</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a><span class="in">`bge-m3`</span> are tied with each other and trail the leaders by 4-5 points</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>at k=10. The q8 (dashed) lines track the full-precision ones within</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>0.5-1 recall point everywhere.</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>We chose to keep <span class="in">`Snowflake-arctic-embed-l-v2.0`</span>.</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hybrid retrieval</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>Hybrid retrieval is the next chapter, but the embedder pick should hold</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>up under both modes, so a preview is useful here.</span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a><span class="al">![Dense vs hybrid recall@k, one panel per family. Hybrid = dense + Qdrant BM25, RRF-fused.](embedder_recall_hybrid.png)</span></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>Recall@10 with the BM25 leg added:</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> family <span class="pp">|</span> dense r@10 <span class="pp">|</span> hybrid r@10 <span class="pp">|</span> lift <span class="pp">|</span></span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> bge-m3 <span class="pp">|</span> 72.5 % <span class="pp">|</span> 76.5 % <span class="pp">|</span> +4.0 <span class="pp">|</span></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Qwen3-0.6B <span class="pp">|</span> 72.9 % <span class="pp">|</span> 77.8 % <span class="pp">|</span> +4.9 <span class="pp">|</span></span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Qwen3-4B <span class="pp">|</span> 75.4 % <span class="pp">|</span> 77.7 % <span class="pp">|</span> +2.3 <span class="pp">|</span></span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> snowflake-arctic-l-v2 <span class="pp">|</span> 76.5 % <span class="pp">|</span> 78.9 % <span class="pp">|</span> +2.4 <span class="pp">|</span></span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a>Hybrid lifts every family, and lifts the weaker dense retrievers more.</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a>The rank order across families is unchanged</span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>after fusion. The embedder choice is robust to retrieval mode.</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>We keep <span class="in">`Snowflake-arctic-embed-l-v2.0`</span> with BM25 hybrid search</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="fu">### Quantization</span></span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>A 568 M model in bf16 is 1.1 GB on disk. The q8 version is 576 MB. On</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a>a 16 GB machine where the pipeline already holds the rest of the pipeline, halving the embedder's memory</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a>footprint is real headroom.</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>The recall cost at k=10 is at most 0.7 points across the four families,</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a>and closes to nothing by k=50. Quality-wise, q8 is free.</span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>We chose <span class="in">`Snowflake-arctic-embed-l-v2.0`</span> quantized to 8 bits with BM25 hybrid search.</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a><span class="fu">### Indexing speed</span></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a><span class="al">![Indexing throughput vs dense recall@10. Top-right wins.](embedder_speed_vs_recall.png)</span></span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>The 568 M and 600 M models index in well under a minute for the</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>581-paragraph corpus (800-3000 tokens/second, depending on family and</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>precision). <span class="in">`Qwen3-4B`</span> is roughly 10× slower (~180 tokens/second; about</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>six minutes to re-index the corpus). At the 100k-paragraph scale a</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a>real-world corpus would have, that is the difference between an embed</span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>step that takes a few minutes and one that takes an hour.</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>q8 is not uniformly faster than full precision on MLX. It is faster for</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a><span class="in">`Snowflake`</span> (1.1×), slightly slower for <span class="in">`bge-m3`</span> and <span class="in">`Qwen3-4B`</span>, and</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>noticeably slower for<span class="in">` Qwen3-0.6B`</span> (2.5× slower). The gap depends on</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>which architecture has a fully-vectorised dequantisation path in</span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a><span class="in">`mlx-embeddings`</span> at this version, and is the kind of thing that closes</span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a>upstream as more families get tuned. For now: treat q8 as a memory and</span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a>disk win, not a speed win.</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a>The cleanest Pareto point on the chart is <span class="in">`snowflake-arctic-l-v2 q8`</span>:</span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>best recall@10 of any sub-1B variant, fastest throughput of any</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a>sub-1B variant.</span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a><span class="fu">### The pick</span></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>**snowflake-arctic-embed-l-v2.0, q8.** Tops dense recall at every k</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>tested, tops hybrid recall too, shares the 568 M size class with <span class="in">`bge-m3`</span>,</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a>and the q8 quantisation gives us a 576 MB on-disk footprint with no</span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>big quality cost.</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reranking</span></span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a>The next logical step after hybrid retrieval is **reranking**: take the</span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a>top-K candidates from the prefetch and re-score them with a more</span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>expensive but more accurate model. The usual reranker family is the</span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>cross-encoder. One model, taking a (query, document) pair, emits a</span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a>relevance score. The catch is cost. A cross-encoder makes one full</span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>forward pass per candidate, and competitive multilingual cross-encoders</span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>are 500M+ parameters. With top-K=50, that is 50 forwards through a</span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a>heavy model per query. Our latency budget is sub-second total; a</span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a>cross-encoder rerank alone would blow that.</span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a>**Late-interaction (ColBERT-style) reranking** offers a different</span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a>trade-off. Each document is encoded once into a sequence of per-token</span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a>vectors at index time and stored on disk. At query time, the query is</span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a>encoded the same way, and the score is a cheap MaxSim aggregation over</span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a>per-token similarities. The work the cross-encoder pays per-pair at</span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a>query time is amortised at index time, paid once per document. The</span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a>model size is similar but the per-query cost drops from "K model</span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a>forwards" to "1 model forward + K small dot-product reductions". That</span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a>shape fits the latency budget. It is also why we already configured the</span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a>late-interaction multi-vector field in Qdrant earlier in the post.</span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a><span class="fu">### The multilingual options</span></span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a>We considered two multilingual late-interaction models:</span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`jinaai/jina-colbert-v2`</span><span class="co">](https://huggingface.co/jinaai/jina-colbert-v2)</span>:</span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a>  559 M parameters, 94 languages, 128-dim per-token vectors.</span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">BAAI/bge-m3 multivector head</span><span class="co">](https://huggingface.co/BAAI/bge-m3)</span>:</span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a>  the same bge-m3 we already load for dense, with its multi-vector head</span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a>  applied to per-token outputs. 1024-dim per token, eight times the</span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a>  storage and the MaxSim compute of jina. It is not Matryoshka-trained,</span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a>  so naively truncating to a comparable 128-d would discard most of the</span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a>  signal in unprincipled ways.</span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a>We picked **jina-colbert-v2**: native low dim, training designed for</span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a>the task, and the multilingual coverage is strictly broader than</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a>bge-m3's.</span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a>We ported jina-colbert-v2 to MLX</span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">`src/rag/embedding/colbert.py`</span><span class="co">](https://github.com/leonnoirclerc/rag/blob/main/src/rag/embedding/colbert.py)</span>)</span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a>on top of the same <span class="in">`xlm-roberta-rope`</span> backbone we vendored from</span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a>mlx-vlm. Storage trick: the multi-vector field in Qdrant has HNSW</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a>disabled (<span class="in">`hnsw_config.m=0`</span>) and lives on disk. It is only ever scored</span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a>exact-MaxSim against the candidates the prefetch returns, so building a</span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a>graph would be wasted work.</span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hit@1 across the four multilingual families</span></span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a><span class="al">![Top-1 precision under dense, +BM25 hybrid, +ColBERT MaxSim rerank (jina-colbert-v2), and both stacked. The reranker here is jina-colbert-v2 in every case. Hybrid (light) is the best column for three of four families.](late_interaction_hit1.png)</span></span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> family <span class="pp">|</span> dense <span class="pp">|</span> hybrid <span class="pp">|</span> +colbert <span class="pp">|</span> hybrid+colbert <span class="pp">|</span></span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> snowflake-l-v2 <span class="pp">|</span> 67.5 <span class="pp">|</span> **76.1** <span class="pp">|</span> 73.1 <span class="pp">|</span> 73.1 <span class="pp">|</span></span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Qwen3-4B <span class="pp">|</span> 68.7 <span class="pp">|</span> **74.5** <span class="pp">|</span> 72.5 <span class="pp">|</span> 73.1 <span class="pp">|</span></span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Qwen3-0.6B <span class="pp">|</span> 70.6 <span class="pp">|</span> **75.4** <span class="pp">|</span> 72.8 <span class="pp">|</span> 72.8 <span class="pp">|</span></span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> bge-m3 <span class="pp">|</span> 68.5 <span class="pp">|</span> 72.3 <span class="pp">|</span> **73.1** <span class="pp">|</span> 73.1 <span class="pp">|</span></span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a>**jina-colbert-v2 does not improve our retrieval.** Hybrid alone wins</span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a>on three of four families. The one family where ColBERT helps (bge-m3)</span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a>gains less than a point. Stacking ColBERT on top of hybrid ties</span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a>"+ColBERT alone" in every family, which means the BM25 leg surfaces</span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a>candidates that ColBERT then deranks back. The two scoring systems</span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a>are not stacking; they are trading.</span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a>The full metric table on snowflake-l-v2 (our picked embedder):</span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> variant <span class="pp">|</span> hit@1 <span class="pp">|</span> hit@5 <span class="pp">|</span> hit@10 <span class="pp">|</span> recall@10 <span class="pp">|</span> mrr <span class="pp">|</span> ndcg@10 <span class="pp">|</span></span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|---:|---:|</span></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> hybrid (no rerank) <span class="pp">|</span> **73.8** | **92.5** | **96.2** | **78.9** | **82.1** | **71.6** <span class="pp">|</span></span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> hybrid + ColBERT <span class="pp">|</span> 73.1 <span class="pp">|</span> 91.9 <span class="pp">|</span> 95.4 <span class="pp">|</span> 76.3 <span class="pp">|</span> 81.4 <span class="pp">|</span> 69.8 <span class="pp">|</span></span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a>Two failure examples make the mechanism concrete. Both are queries</span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a>where snowflake-hybrid had the right paragraph at rank 1 and ColBERT</span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a>then demoted it.</span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Q:** *"What two-stage process does DeepSeek-V4-Flash follow when</span></span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; introducing sparse attention during training, and at what sequence</span></span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; length and token count is sparsity first activated?"*</span></span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Hybrid rank 1 (correct):** the training-recipe paragraph with the</span></span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; sparsity schedule and the token-count cutoffs.</span></span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **ColBERT rank 1 (wrong):** the paper's abstract, which mentions</span></span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "DeepSeek-V4-Flash", "sparse attention", and "training" multiple</span></span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; times but does not answer the specific question.</span></span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Right answer demoted to rank 16.</span></span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Why ColBERT failed here.** The abstract has many tokens that match</span></span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; the query's topic words. MaxSim sums those matches, so the abstract</span></span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; scores high. The specific training paragraph mentions the same topic</span></span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; words fewer times and loses on token count, even though it actually</span></span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; contains the answer.</span></span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Q:** *"How are the authors of the DeepSeek-V4 paper listed, and</span></span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; what does the asterisk (*) notation next to certain author names</span></span>
<span id="cb1-545"><a href="#cb1-545" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; indicate?"*</span></span>
<span id="cb1-546"><a href="#cb1-546" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-547"><a href="#cb1-547" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Hybrid rank 1 (correct):** the two-sentence answer, exactly:</span></span>
<span id="cb1-548"><a href="#cb1-548" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *"Authors are listed alphabetically by their first name. Names marked</span></span>
<span id="cb1-549"><a href="#cb1-549" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; with * denote individuals who have departed from our team."*</span></span>
<span id="cb1-550"><a href="#cb1-550" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-551"><a href="#cb1-551" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **ColBERT rank 1 (wrong):** an unrelated paragraph about</span></span>
<span id="cb1-552"><a href="#cb1-552" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Mixture-of-Experts architecture that happens to mention "DeepSeek-V4".</span></span>
<span id="cb1-553"><a href="#cb1-553" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-554"><a href="#cb1-554" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Right answer demoted to rank 8.</span></span>
<span id="cb1-555"><a href="#cb1-555" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-556"><a href="#cb1-556" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Why ColBERT failed here.** The right answer is short, about 25</span></span>
<span id="cb1-557"><a href="#cb1-557" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; tokens. MaxSim's score scales with the number of high-similarity doc</span></span>
<span id="cb1-558"><a href="#cb1-558" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; tokens, so short answers are systematically under-scored. The long</span></span>
<span id="cb1-559"><a href="#cb1-559" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; MoE paragraph wins on token count.</span></span>
<span id="cb1-560"><a href="#cb1-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-561"><a href="#cb1-561" aria-hidden="true" tabindex="-1"></a>The pattern across the 41 cases where ColBERT demoted the right answer</span>
<span id="cb1-562"><a href="#cb1-562" aria-hidden="true" tabindex="-1"></a>is consistent: it rewards token-rich generic content; BM25's IDF</span>
<span id="cb1-563"><a href="#cb1-563" aria-hidden="true" tabindex="-1"></a>weighting rewards rare-word matches that pinpoint specific answers. On</span>
<span id="cb1-564"><a href="#cb1-564" aria-hidden="true" tabindex="-1"></a>a corpus of short technical paragraphs answering specific questions,</span>
<span id="cb1-565"><a href="#cb1-565" aria-hidden="true" tabindex="-1"></a>hybrid retrieval is the right tool. ColBERT was built for a different</span>
<span id="cb1-566"><a href="#cb1-566" aria-hidden="true" tabindex="-1"></a>corpus shape.</span>
<span id="cb1-567"><a href="#cb1-567" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-568"><a href="#cb1-568" aria-hidden="true" tabindex="-1"></a><span class="fu">### What we ship</span></span>
<span id="cb1-569"><a href="#cb1-569" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-570"><a href="#cb1-570" aria-hidden="true" tabindex="-1"></a>The retrieval pipeline stops at **dense + BM25 with RRF fusion**.</span>
<span id="cb1-571"><a href="#cb1-571" aria-hidden="true" tabindex="-1"></a>ColBERT MaxSim does not earn its keep on this corpus, and stacking it</span>
<span id="cb1-572"><a href="#cb1-572" aria-hidden="true" tabindex="-1"></a>on top of hybrid does not help in any family. We keep the MLX</span>
<span id="cb1-573"><a href="#cb1-573" aria-hidden="true" tabindex="-1"></a><span class="in">`jina-colbert-v2`</span> port in the codebase as a documented building block. If</span>
<span id="cb1-574"><a href="#cb1-574" aria-hidden="true" tabindex="-1"></a>the corpus later shifts to long documents or to an out-of-domain mix,</span>
<span id="cb1-575"><a href="#cb1-575" aria-hidden="true" tabindex="-1"></a>this is the obvious next thing to revisit.</span>
<span id="cb1-576"><a href="#cb1-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-577"><a href="#cb1-577" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-578"><a href="#cb1-578" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-579"><a href="#cb1-579" aria-hidden="true" tabindex="-1"></a>**Code state at time of writing:** <span class="co">[</span><span class="ot">`d72e899`</span><span class="co">](https://github.com/leonnoirclerc/rag/commit/d72e8993f047c6b559062edfb7e5156299e8f33c)</span>.</span>
<span id="cb1-580"><a href="#cb1-580" aria-hidden="true" tabindex="-1"></a>**Reproduce the parsing numbers:** <span class="in">`uv run python -m benchmark.pdf_pipeline --variants codeformulav2_mlx`</span>.</span>
<span id="cb1-581"><a href="#cb1-581" aria-hidden="true" tabindex="-1"></a>**Reproduce the embedder + late-interaction sweeps:** <span class="in">`uv run python -m eval.sweep`</span>.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Leon Noirclerc</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/leonnoirclerc">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>
(function () {
  function tagCategories() {
    document.querySelectorAll('.listing-category').forEach(function (el) {
      var slug = (el.textContent || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      if (slug) el.classList.add('cat-' + slug);
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', tagCategories);
  } else {
    tagCategories();
  }
})();
</script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>